name: Mutation testing

on:
    workflow_dispatch:
    workflow_run:
        workflows: [CI]
        types: [completed]
        branches: [master]

env:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: 1

jobs:
    mutation_testing:
        name: Mutation tests
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/install-action@v2
              with:
                  tool: cargo-mutants
            - run: cargo mutants -p troc-core --exclude-re troc-core/benches --exclude-re troc-core/src/common --exclude-re troc-core/src/messages --exclude-re troc-core/src/types/ -vV
            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: mutants-out
                  path: mutants.out
